[package]
name = "cartographer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-fuzzy-search = "0.1.1"
terminal = "0.2.1"
