
Output example_menu.gif

Set FontSize 32
Set Width 1200
Set Height 600

Hide
Type "cargo build --example example_menu"
Enter
Type "cd ../../target/debug/examples"
Enter
Type "clear"
Enter
Type "./example_menu"
Enter

Show


Set TypingSpeed 400ms

Sleep 2s
Down
Sleep 2s
Up
Sleep 1s
Up
Sleep 2s

Space
Sleep 1s
Down
Sleep 0.5s
Space
Sleep 1s
Down
Sleep 0.5s
Space

Type "Ok"

Sleep 2s
Down
Sleep 1s
Space
Sleep 2s

Enter

Sleep 5s
